---
driver:
  name: docker
  privileged: true
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /dev/fuse:/dev/fuse

provisioner:
  name: puppet_apply
  manifests_path: spec/manifests
  hiera_data_path: hieradata
  hiera_deep_merge: true
  puppet_verbose: true
  require_chef_for_busser: false

platforms:
  - name: "ubuntu-18.04-puppet"
    driver:
      instance_name: "ubuntu-18.04-puppet"
      image: diodonfrost/ubuntu-18.04-puppet
      run_command: /sbin/init
      platform: ubuntu
      provision_command:
        - apt-get install -y init
        - apt-get install -y fuse snapd snap-confine squashfuse sudo
        - dpkg-divert --local --rename --add /sbin/udevadm && ln -s /bin/true /sbin/udevadm

  - name: "ubuntu-16.04-puppet"
    driver:
      instance_name: "ubuntu-16.04-puppet"
      image: diodonfrost/ubuntu-16.04-puppet
      run_command: /sbin/init
      platform: ubuntu
      provision_command:
        - apt-get install -y init
        - apt-get install -y fuse snapd snap-confine squashfuse sudo
        - dpkg-divert --local --rename --add /sbin/udevadm && ln -s /bin/true /sbin/udevadm

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: spec/inspec

suites:
  - name: default
