---
language: ruby
rvm: 2.4.1
services:
  - docker

env:
  - distribution: ubuntu
    version: "18.04"
    number: "18-04"
  - distribution: ubuntu
    version: "16.04"
    number: "16-04"

before_install:
  # Build docker container
  - 'sudo docker pull diodonfrost/${distribution}-${version}-puppet'

script:

  # Launch kitchen build, puppet apply and tests
  - 'kitchen test default-${distribution}.${number}'

  # Delete container
  - 'sudo docker system prune -f -a'
