ubuntu_laptop::packages::install::os_packages:
  - cryptsetup
  - ecryptfs-utils
  - filezilla
  - git
  - golang
  - keepassx
  - libssl-dev
  - nmap
  - openssh-server
  - openvpn
  - python
  - python-dev
  - python-pip
  - terminator
  - vim
  - virtualbox
  - vlc
  - wget
  - wireshark
